* Temperance

🌗 A color scheme for human eyes looking at terminal emulators.

See the colors [[https://publik-void.github.io/temperance-color-scheme/][here]].

I recommend ~temperance-day~ when working in well-lit environments and
~temperance-dusk~ when working in dark environments.

** Context

The color scheme is based on the following design specifications:
- Have a dark and a light version
- Have a cold (blue-tinted) and a warm (orange-tinted) version
  - special focus should be on the warm version to make sure it reduces blue
  light exposure from usually blue-heavy screens somewhat
- Have a deliberately decreased contrast range
- Have two extra variants with maximized contrast (full black and white)
  - e.g. for working in the sun on a not-so-bright display
- To keep some distance between foreground and background colors, even without
  full contrast, use roughly opposite color hues
- Create a sort of color intensity gradient with the black and white colors
  and their intense versions. Have the foreground color be somewhere in the
  middle
- Use roughly isoluminant colors for the ANSI colors and try to adhere to the
  naming
- Work in (polar) CIELAB colorspace

This set of specifications almost invariably creates a [[https://ethanschoonover.com/solarized][Solarized]]-like
colorscheme, plus a complement of warm dark and cold light versions. (And then
of course the high-contrast versions.) While having been inspired by Solarized,
the specifications have not been chosen to simply make a recreation of it (or
to even try to live up to it). The main goals of this colorscheme are to play
nicely with terminals and to be eye-friendly, especially with regards to of blue
light exposure.

** Usage as a Vim color scheme

In my humble opinion, the color scheme should be the responsibility of the
terminal emulator, while applications running inside of it should work with the
abstracted named colors. Thus, I recommend [[https://github.com/jeffkreeftmeijer/vim-dim][vim-dim]].
Temperance has been designed to work with it, though I do apply [[https://github.com/publik-void/config-nvim/blob/master/include/my_dim_colorscheme.vim][some minor modifications in my vim configuration]].

** Re-building

#+begin_src sh
julia --threads=auto --project=. -e 'import Pkg; Pkg.instantiate()'
julia --threads=auto --project=. temperance-color-scheme.jl
#+end_src

